#!/usr/bin/env bash
# this script transfers a file from a client to a server
# it accepts 4 parameters as command line arguments
# these are then used with the scp command
if [ "$#" -lt 4 ]
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
   scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2":~
fi
