#!/usr/bin/env bash
# installs nginx on webserver
# changes default webpage to print "Holberton School"
sudo apt-get update
sudo apt-get install -y nginx

sudo mkdir /etc/nginx/html
sudo touch /etc/nginx/html/index.html
echo "Holberton School" > /etc/nginx/html/index.html
printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /etc/nginx/html;
     index       index.html index.html;
}
" > /etc/nginx/sites-available/default

sudo service nginx restart
