#!/usr/bin/env bash
# generates a mysql dump
# creates compressed archive of the mysql dump

mysqldump -uroot -p"$1" --all-databases > backup.sql

if [ -f backup,sql ]
then
    tar cfz "$(date '+%Y-%m-%d').tar.gz" backup.sql
fi
