#!/usr/bin/env bash
# Creates the file /var/run/holbertonscript.pid containing its PID
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/holbertonscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal

i="1"
sudo touch /var/run/holbertonscript.pid
sudo bash -c 'echo $$ > /var/run/holbertonscript.pid'
while [ $i -eq 1 ]
do
echo "To infinity and beyond"
sleep 2
trap 'echo "Y U no love me?!"; exit' SIGINT
trap 'echo "I hate the kill command"; sudo rm var/run/holbertonscript.pid; exit' SIGTERM
trap 'sudo rm /var/run/holbertonscript.pid; exit' SIGQUIT
done
