#!/usr/bin/env bash
# displays the content of the current directory in a list format
# only part of the name after the first dash is displayed

list=$(ls)
for i in $list
do
  cut -d- -f2 <<< "$i"
done
