#!/usr/bin/env bash
# checks if file exists and prints messages based on condition
# the checks if file is empty or not and if file is a regular file or not
if [ -e holbertonschool ]
then
	echo "holbertonschool file exists"
	if [ -s holbertonschool ]
	then
		echo "holbertonschool file is empty"
	else
		echo "holbertonschool file is not empty"
	fi
	if [ -f holbertonschool ]
	then
		echo "holbertonschool is a regular file"
	fi
else
	echo "holbertonschool file does not exist"
fi
