#!/usr/bin/env bash
# Script configures Ubuntu server with
# localhost resolving to 127.0.0.2
# facebook.com resolving to 8.8.8.8

cp /etc/hosts ~/hosts.new
sed -i s/127.0.0.1/127.0.0.2/ ~/hosts.new
echo "8.8.8.8		facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
